version: '3.8'

services:
  db:
    image: mysql:5.7
    container_name: django_db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: taskshare_db
      MYSQL_USER: root 
      MYSQL_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - django_network

  web:
    build: .
    container_name: django_web
    command: ["gunicorn", "--bind", "0.0.0.0:8000", "taskshare.wsgi:application"]
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DEBUG=False
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=mydatabase
      - DB_USER=myuser
      - DB_PASSWORD=mypassword
    networks:
      - django_network

volumes:
  mysql_data:

networks:
  django_network:
    driver: bridge
