# Generated by Django 5.1.4 on 2024-12-12 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_remove_task_title_task_deadline_task_task_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='task',
            name='report',
            field=models.TextField(blank=True, null=True),
        ),
    ]
